plugins {
    id 'java'
    id 'net.neoforged.gradle.userdev' version '7.0.145'
}

group = 'net.shadowmage.ancientwarfare'
version = '1.0.0-1.21.1'

java.toolchain.languageVersion = JavaLanguageVersion.of(21)


runs {
    configureEach {
        modSource project.sourceSets.main
    }
    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', 'ancientwarfare'
    }
    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', 'ancientwarfare'
        programArgument '--nogui'
    }
    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', 'ancientwarfare'
    }
    data {
        programArguments.addAll '--mod', 'ancientwarfare', '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.java.srcDirs = ['src/main/java']
sourceSets.main.resources.srcDirs = ['src/main/resources']

sourceSets.main.java.exclude 'net/shadowmage/ancientwarfare/core/**/*.java'
sourceSets.main.java.exclude 'net/shadowmage/ancientwarfare/automation/**/*.java'
sourceSets.main.java.exclude 'net/shadowmage/ancientwarfare/npc/**/*.java'
sourceSets.main.java.exclude 'net/shadowmage/ancientwarfare/structure/**/*.java'
sourceSets.main.java.exclude 'net/shadowmage/ancientwarfare/vehicle/**/*.java'
sourceSets.main.java.exclude 'net/shadowmage/ancientwarfare/model/**/*.java'

repositories {
    mavenCentral()
}

dependencies {
    implementation "net.neoforged:neoforge:21.1.84"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
